project: Projet Test
vcs:
    type:       git
    url:        git@gitlab.actualys.com:international-transport-forum/itf-2013.git
    extra_args: ~
notification:
    - type: mail
      transport:
          host:     localhost
          port:     25
          security: ~
          login:    ~
          password: ~
      message:
          from:     ~
          to:       sebastien@malot.fr
          subject:  Cerbere Notification System
      level: security

    - type:  console
      level: all
drupal:
    path:
        - sites/all/modules/contrib

