language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update || true
  - composer install
  - composer require "drush/drush:*"
  - composer --prefer-source --dev install

script: ./vendor/bin/atoum -d lib/Cerbere/Tests/Units/ -ncc
