language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - HHMV

matrix:
  allow_failures:
    - php: 7
    - php: HHVM
    - env: DRUSH_VERSION=dev-master

env:
  - DRUSH_VERSION=8.*
  - DRUSH_VERSION=dev-master # 9.x

before_script:
  - composer self-update || true
  - composer --prefer-source install
  - composer require drush/drush:$DRUSH_VERSION --ignore-platform-reqs

script: ./vendor/atoum/atoum/bin/atoum -d lib/Cerbere/Tests/Units/ -ncc
